feat: additional parameter support
terraform-ibm-modules/terraform-ibm-cloudant pull request #90
Opened 2024-02-06 20:23 UTC by Aayush-Abhyarthi

### Description

Cloudant module missed some parameters as argument reference. This PR adds those.

https://github.ibm.com/GoldenEye/issues/issues/4584

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2024-02-06 20:23 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-02-06 21:16 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-02-19 21:41 UTC, Aayush-Abhyarthi commented
The upgrade test failed with the following error:-
<img width="1490" alt="Screenshot 2024-02-20 at 3 09 34 AM" src="https://github.com/terraform-ibm-modules/terraform-ibm-cloudant/assets/122350533/ac8e7f80-66c9-44a1-b801-ea0128e6f129">
resources were getting updated

2024-02-27 12:27 UTC, ocofaigh requested changes
These changed need to be also made in `modules/fscloud` and `solutions/dedicated`

2024-02-27 12:27 UTC, ocofaigh commented on variables.tf
> +  default     = true
I would default this `false` and create a commit with `UNSKIP UPGRADE TEST` so we dont have to skip it

2024-02-28 21:18 UTC, Aayush-Abhyarthi commented
/run pipeline

2024-02-29 09:47 UTC, Aayush-Abhyarthi commented
<img width="1402" alt="Screenshot 2024-02-29 at 3 07 49 PM" src="https://github.com/terraform-ibm-modules/terraform-ibm-cloudant/assets/122350533/e9e0a608-3e24-48c8-8c17-dda523c71fc9">

even after making the default value of the enable_cors as false, the infrastructure is getting updated

2024-03-26 14:56 UTC, ocofaigh commented
@Aayush-Abhyarthi thanks for checking - since its an update in place, its fine to skip the upgrade test as long as we include it in the release notes. 
Since you unskipped the upgrade test, you may not be able to skip it again. If this is the case can you create a new PR please?

2024-04-01 20:05 UTC, Aayush-Abhyarthi commented
https://github.com/terraform-ibm-modules/terraform-ibm-cloudant/pull/121

2024-06-03 19:07 UTC, closed without merging